### ISSUE TITLE
Desarrollo inicial de vista persona-fieldset

### ISSUE THREAD

**Issue by ivancas84** [ivancas84/magistrados-angular#7]
* [x] Analizar Datepicker: [material-angular datepicker](https://material.angular.io/components/datepicker/overview)
* [x] Incorporar Datepicker: [angular-gen-md](https://github.com/ivancas84/angular-gen-md/issues/5)
* [x] Desarrollar componente general Select: [angular-core-md](https://github.com/ivancas84/angular-core-md/issues/10)
* [x] Incorporar titulos en autocomplete y select.
* [x] Incorporar visualizacion de error required en select
* [x] Incorporar validación de email: [angular-gen-md](https://github.com/ivancas84/angular-gen-md/issues/10)
* [x] Insertar valores iniciales en base de datos
* [x] Analizar formato e idioma de fecha: [material.angular datepicker internationalization](https://material.angular.io/components/datepicker/overview#internationalization)

**Comment by ivancas84** [comment]
### Tareas adicionales
* [Analizar Datepicker](https://material.angular.io/components/datepicker/overview)
